version: "3.8"
services:
  app:
    build: ./.container/php
    volumes:
      - ./work:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./work:/work
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./.container/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: